markdown: kramdown
permalink: licode/:title.html
destination: ./site/
exclude:
  - Rakefile
  - Gemfile
  - .gitignore
  - node_modules
baseurl: /
domain: lynckia.com
title: Licode - Open Source Communication Provider
author: Lynckia
web: http://www.lynckia.com
twitter: lynckia
github: ging/licode
feedburner:
  id: lynckia
gems:
  - jekyll-redirect-from
